services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sende
      POSTGRES_PASSWORD: sende_dev_password
      POSTGRES_DB: sende
    ports:
      - "5432:5432"
    volumes:
      - sende_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  sende_pg_data:
